name: Generate Allure Report and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' si usas otra rama como principal

jobs:
  generate-report:
    runs-on: ubuntu-latest  # Usa un runner de Ubuntu, puedes cambiarlo a Windows si prefieres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Cambia la versión si es necesario

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r proyecto/requirements.txt

      - name: Install Allure Behave formatter
        run: |
          pip install allure-behave

      - name: Install Allure Commandline
        run: |
          npm install -g allure-commandline --save-dev  # Instalar Allure Commandline

      - name: List project files for debugging
        run: |
          cd proyecto/Tests_BDD
          ls -R  # Verifica la estructura de directorios y archivos

      - name: Generate Allure results
        run: |
          cd proyecto/Tests_BDD
          behave -f allure_behave.formatter:AllureFormatter -o allure-results ./Features

      - name: Generate HTML report
        run: |
          cd proyecto/Tests_BDD
          allure generate allure-results --clean -o allure-report

      - name: Create Reports folder
        run: |
          mkdir -p proyecto/Reportes  # Crear el directorio si no existe
          mv proyecto/Tests_BDD/allure-report/ proyecto/Reportes/  # Mover el reporte HTML generado

      - name: Set up Git for deployment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Guardar los cambios locales antes del checkout
      - name: Commit local changes
        run: |
          git add .  # Agrega los cambios
          git commit -m "Saving analysis reports" || echo "No changes to commit"  # Confirmar los cambios si los hay

      - name: Deploy Reports folder to GitHub Pages
        run: |
          git fetch origin gh-pages  # Obtiene la última versión de la rama gh-pages
          git checkout gh-pages  # Cambia a la rama gh-pages
          cp -r proyecto/Reportes/* .  # Copia el contenido de la carpeta Reportes
          git add .  # Agrega todos los archivos copiados
          git commit -m "Deploy Allure report to gh-pages" || echo "No changes to commit"  # Manejo de caso si no hay cambios
          git push origin gh-pages  # Publica los cambios en la rama gh-pages
