name: Mutant Testing Report
on:
  push:
    branches:
      - main

jobs:
  mutmut:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives the workflow permission to push to gh-pages
    steps:
    # Checkout the repository with full history
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetches full history for branch operations

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install mutmut==2.0.0
        pip install pytest
        pip install -r proyecto/requirements.txt

    # Run mutmut tests
    - name: Run mutmut
      run: |
        cd proyecto
        mutmut run --paths-to-mutate classes/
        mutmut html

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./proyecto/mutmut_html
        publish_branch: gh-pages
        force_orphan: true