name: Mutant Testing Report

on:
  push:
    branches: [ main ]

jobs:
  mutant-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install mutmut==2.0.0
        pip install pytest
        pip install -r proyecto/requirements.txt

    - name: Run mutmut
      continue-on-error: true
      run: |
        cd proyecto
        mutmut run --paths-to-mutate classes/

    - name: Reporte mutmut
      continue-on-error: true
      run: |
        cd proyecto
        mutmut html

    - name: Mover index.html a report_mutante
      run: |
        mkdir -p proyecto/html/report_mutante  # Crear la carpeta 'report_mutante' si no existe
        mv proyecto/html/index.html proyecto/html/report_mutante/  # Mover el archivo index.html

    - name: Configurar Git para publicar en GitHub Pages
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Prepare gh-pages branch and deploy report
      run: |
        # Obtiene la última versión de la rama gh-pages
        git fetch origin gh-pages || echo "No previous gh-pages branch"
        
        # Si la rama gh-pages existe, realiza un pull para obtener los cambios remotos
        git checkout gh-pages || git checkout -b gh-pages

        # Actualiza la rama local con los cambios remotos
        git pull origin gh-pages --rebase || git pull origin gh-pages  # Rebase o merge según lo que prefieras

        # Mueve el directorio report_mutante a la raíz de la rama gh-pages
        cp -r proyecto/html/report_mutante/* .  # Copia el contenido de report_mutante al directorio raíz

        # Añadir los archivos al repositorio
        git add .

        # Realiza commit si hay cambios
        git commit -m "Publicando reporte de Mutant Testing" || echo "No hay cambios para commitear"

        # Empuja los cambios a la rama gh-pages
        git push origin gh-pages
