name: Run SonarCloud Analysis and Deploy Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Revisar el código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Instalar dependencias
      - name: Install dependencies
        run: |
          pip install -r proyecto/requirements.txt

      # Paso 3: Ejecutar pruebas con cobertura y generar XML + HTML
      - name: Run tests with coverage
        run: |
          cd proyecto
          pytest --cov=. --cov-report=xml:report_coverage/coverage.xml --cov-report=html:report_coverage/html_report

      # Paso 4: Ejecutar análisis en SonarCloud
      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd proyecto
          sonar-scanner -Dsonar.projectKey=jaimeflores_flaskapp \
            -Dsonar.organization=jaimeflores \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.python.coverage.reportPaths=proyecto/report_coverage/coverage.xml \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Paso 5: Crear carpeta de reportes
      - name: Create Reports folder
        run: |
          mkdir -p Reportes  # Crear el directorio si no existe
          mv proyecto/report_coverage/html_report/index.html Reportes/reporte-sonar.html  # Mover el reporte HTML a la carpeta de reportes

      # Paso 6: Configurar Git para publicar en GitHub Pages
      - name: Configure Git for GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      # Paso 7: Publicar el reporte en GitHub Pages
      - name: Publish report to GitHub Pages
        run: |
          git fetch origin gh-pages  # Obtener la última versión de la rama gh-pages
          git checkout gh-pages  # Cambiar a la rama gh-pages
          cp Reportes/reporte-sonar.html reporte-sonar.html  # Copiar el archivo a la rama gh-pages
          git add reporte-sonar.html
          git commit -m "Publishing SonarCloud coverage report as reporte-sonar.html" || echo "No changes to commit"  # Manejo de caso si no hay cambios
          git push origin gh-pages  # Publicar sin usar --force
