name: Run SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Revisar el código desde el repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: |
        pip install -r proyecto/requirements.txt

    # Paso 4: Ejecutar pruebas con cobertura
    - name: Run tests with coverage
      run: |
        cd proyecto
        pytest --cov=. --cov-report=xml:report_coverage/coverage.xml

    # Paso 5: Subir resultados de cobertura a SonarCloud
    - name: Run SonarCloud Analysis
      run: |
        cd proyecto
        sonar-scanner -Dsonar.projectKey=jaimeflores_flaskapp \
          -Dsonar.organization=jaimeflores \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.python.coverage.reportPaths=proyecto/report_coverage/coverage.xml
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
